#server:
#  port: 8080
#  servlet:
#    context-path: /identity

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/busdb
    username: root
    password: chithien26@

#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/busdb?useSSL=false&serverTimezone=UTC
#    username: root
#    password: chithien26@
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true